# Completeness rule
from __future__ import annotations

MANDATORY_COLUMNS: dict[str, list[str]] = {
    "customers_expanded": [
        "country", "le_book", "customer_id", "salutation", "customer_name",
        "surname", "forename_1", "forename_2", "customer_gender",
        "customer_acronym", "vision_ouc", "vision_sbu", "account_officer",
        "naics_code", "nationality", "residence", "economic_sub_sector_code_isic",
        "related_party", "customer_open_date", "customer_tin", "ssn_number",
        "national_id_type", "national_id_number", "health_insurance_number",
        "customer_status", "employer_name", "date_of_birth", "place_of_birth",
        "perm_address_1", "perm_address_2", "perm_village", "perm_country",
        "comm_address_1", "comm_address_2", "comm_village", "comm_country",
        "comm_residence_type", "marital_status", "spouse_name",
        "number_of_dependants", "emp_address_1", "emp_address_2",
        "emp_village", "emp_country", "email_id", "work_telephone",
        "home_telephone", "fax_number_1", "fax_number_2", "relationship_type",
        "internet_banking_subscription", "mobile_banking_subscription",
        "employee_id", "occupation", "income", "income_frequency",
        "group_name", "group_number", "legal_status", "local_govt_member",
        "date_last_modified", "education", "social_economic_class",
        "next_of_kin_name", "next_of_kin_id_type", "next_of_kin_telephone",
        "next_of_kin_email_id", "account_mandate_name", "account_mandate_id_type",
        "account_mandate_id_number", "related_party_name",
    ],
    "accounts": [
        "country", "le_book", "account_no", "customer_id", "currency",
        "account_name", "vision_gl", "vision_ouc", "vision_sbu",
        "account_officer", "account_type", "account_indicator", "gl_enrich_id",
        "account_open_date", "freeze_status", "economic_sub_sector_code",
        "economic_sub_sector_code_isic", "public_sector_code",
        "institutional_sector_code", "credit_nature", "credit_category",
        "interest_rate_dr", "interest_rate_cr", "account_status",
        "account_status_date",
          "record_indicator",
        "maker", "verifier",
        "internal_status", "date_last_modified", "date_creation",
    ],
    "contracts_disburse": [
        "country", "le_book", "business_date", "contract_id", "currency",
        "current_disbursed_amt", "previous_disbursed_amt", "first_payment_date",
        "contract_status_nt", "contract_status", "record_indicator_nt",
        "record_indicator", "maker", "verifier", "internal_status",
        "date_last_modified", "date_creation",
    ],
    "contract_loans": [
        "contract_sequence_number", "country", "le_book", "year_month",
        "prev_loan_paid", "loan_in_other_institution", "loan_purpose",
        "renigo_flag", "approval_date", "declaration_date", "available_amount",
        "emi_amount", "outstanding_amount_fcy", "outstanding_amount_lcy",
        "general_provision_lcy", "specific_provision_lcy",
        "loan_includ_interest", "overdraft_includ_interest",
        "other_cr_includ_interest", "collateral_accepted", "suspense_interest",
        "provision_held", "overdft_outstand_amt", "overdft_provisions",
        "oth_credit_outstand_amt", "oth_credit_provision", "coll_accept_bnr",
        "cash_back", "security_issued", "collateral_received",
        "guarante_iss_rw_bank", "guarante_iss_fg_bank",
        "securities_regularly_trend", "interest_rate_dr", "physical_guarantee",
        "guarantee_amount", "compulsory_saving", "loan_reschedule_date",
        "loan_reschedule_type", "repayment_frequency", "performance_class",
        "grace_period_accorded", "sche_first_pay_date", "latest_payment_date",
        "instalments_in_arrears", "num_of_instalments", "num_instalments_paid",
        "total_amt_repaid_prin_lcy", "non_perf_loan_bal_lcy",
        "shareholder_paid_amt_lcy", "defaulter_action_taken",
        "total_instalments_paid", "total_instalments_outstanding",
        # "written_off_date", "written_off_loans_lcy", "govt_schemes",
        # "govt_scheme_financed", "contract_loan_status", "record_indicator",
        # "maker", "verifier", "internal_status", "date_last_modified",
        # "date_creation", "disbursed_amount", "prin_outstanding_amt_fcy",
        # "prin_outstanding_amt_lcy", "interest_due_fcy", "interest_due_lcy",
        # "regulatory_provision", "date_of_provision", "other_cr_penalties",
        # "other_charges", "date_past_due",
        # "due_amount",
    ],
    "contract_schedules": [
        "contract_sequence_number", "country", "le_book", "schedule_date",
        "payment_date", "emi_amount", "due_amount", "principal_amount_due",
        "int_amount_due", "add_int_amount_due", "principal_amount_paid",
        "int_amount_paid", "add_int_amount_paid", "outstanding_amount",
        "maker", "verifier", "internal_status", "date_last_modified",
        "date_creation", "principal_amount_due_fcy", "int_amount_due_fcy",
        "principal_amount_paid_fcy", "int_amount_paid_fcy",
        "outstanding_amount_fcy",
    ],
    "contracts_expanded": [
        "contract_sequence_number", "country", "le_book", "customer_id",
        "contract_id", "record_type", "source_id", "account_officer",
        "issue_id", "deal_type", "deal_sub_type", "start_date", "maturity_date",
        "settlement_date", "days_remaining_mat", "days_start_mat",
        "contract_status", "principal_gl", "principal_amount_lcy",
        "principal_amount_fcy", "mis_currency", "interest_rate_dr",
        "interest_rate_cr", "interest_rate_method", "cost_of_funds_rate",
        "gl_enrich_id", "status", "number_of_units", "strike_price",
        "vega", "gamma", "delta", "option_type", "put_call_ind",
        "hedge_trading_ind", "portfolio_type", "volatility_index_basket",
        "undly_vol_index_basket", "underlying", "trade_ref_no",
        "trade_product_status", "option_description", "trader_id", "purpose",
        "underlying_maturity_date", "underlying_start_date", "yield",
        "hedge_p_and_l", "agent", "commissson_ccy",
        "cash_collateral_percentage", "commission_percentage",
        "current_account_no", "extension_date", "last_negotiation_date",
        "beneficiary", "res_mortage_collateral_type", "res_mortage_market_value",
        "res_dis_value", "com_mortage_collateral_type",
        "com_mortage_market_value", "com_dis_value", "guarantor_credit_line",
        "guarantor_customer_id", "borrower_category_code", "purpose_of_advance",
        "type_of_advance", "nature_of_advance", "guarantee_cover_code",
        "performance_class", "sub_performance_class", "lcy_equiv_inception",
        "exchange_rate", "option_exercise_date", "futures_market_price",
        "futures_cost_price", "fut_var_margin", "contract_attribute_1",
        "contract_attribute_2", "contract_attribute_3",
        "latest_repayment_schedule", "latest_repayent_frequency",
        "no_of_tenors", "applicable_date", "date_past_due", "dpd_amount",
        "contract_dpd_status", "record_indicator", "maker", "verifier",
        "internal_status", "date_last_modified", "date_creation",
        "govt_schemes_flag", "apr_rate", "contract_application_fee",
        "contract_administrative_fee", "other_contract_charges", "commissions",
        "insured_flag", "contract_insurance_charges", "ins_expiry_date",
        "interest_gl", "interest_amount_fcy", "interest_amount_lcy",
        "loan_application_id", "policy_type", "num_of_covered_persons",
        "sum_insured", "assured", "commence_date", "benefit_expiry_date",
        "premium_payment_freq", "sum_reassured", "pension_contract_status",
    ],
    "loan_applications_2": [
        "country", "le_book", "loan_application_id", "loan_application_type",
        "business_date", "customer_id", "customer_name", "customer_gender",
        "loan_utilization_location",
        "vision_ouc", "loan_purpose",
        "vision_sbu", "economic_sector_code", "application_date",
        "application_status", "currency", "applied_amount_lcy",
        "applied_amount_fcy", "approved_amount_lcy", "approved_amount_fcy",
        "rejection_reason", "prev_loan_paid",
    ],
    "prev_loan_applications": [
        "country", "le_book", "business_date", "loan_application_id",
        "prev_contract_id", "prev_cont_modif_reason_at", "prev_cont_modif_reason",
        "prev_loan_app_status_nt", "prev_loan_app_status",
        "record_indicator_nt", "record_indicator", "maker", "verifier",
        "internal_status", "date_last_modified", "date_creation",
    ],
}

# One completeness rule per table
_COMP_TABLE_NAMES = {
    "COMP-001": "customers_expanded",
    "COMP-002": "accounts",
    "COMP-003": "contracts_disburse",
    "COMP-004": "contract_loans",
    "COMP-005": "contract_schedules",
    "COMP-006": "contracts_expanded",
    "COMP-007": "loan_applications_2",
    "COMP-008": "prev_loan_applications",
}

COMP_RULE_META = {}

for rid, tbl in _COMP_TABLE_NAMES.items():

    COMP_RULE_META[rid] = {
        "name": f"All mandatory columns must be non-null ({tbl})",
        "category": "Field Completeness",
        "dimension": "completeness",
        "tables": [tbl],
        "fields": MANDATORY_COLUMNS[tbl],
    }

